/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tgraficacion;
import java.awt.*;
/**
 *
 * @author Jose Eduardo Madrigal Osorio
 * 
 */
public class DPoligonoTraslacion extends javax.swing.JFrame {
    
    int [][] poligono = {
        
{130,50,110,50},
{110,50,90,90},
{90,90,115,155},
{115,155,135,180},
{135,180,170,150},
{170,150,155,235},
{155,235,160,290},
{160,290,150,330},
{150,330,160,290},
{160,290,155,235},
{155,235,170,150},
{170,150,170,235},
{170,235,174,280},
{174,280,181,280},
{181,280,185,235},
{185,235,185,150},
{185,150,200,235},
{200,235,195,290},
{195,290,205,330},
{205,330,195,290},
{195,290,200,235},
{200,235,185,150},
{185,150,220,180},
{220,180,240,155},
{240,155,265,90},
{265,90,245,50},
{245,50,225,50},
{225,50,185,85},
{185,85,210,35},
{210,35,205,5},
{205,5,210,35},
{210,35,185,85},
{185,85,185,50},
{185,50,181,30},
{181,30,182,29},
{182,29,183,28},
{183,28,181,30},
{181,30,174,30},
{174,30,170,50},
{170,50,174,30},
{174,30,173,29},
{173,29,174,28},
{174,28,174,30},
{174,30,170,50},
{170,50,185,50},
{185,50,169,50},
{169,50,170,85},
{170,85,145,35},
{145,35,155,5},
{155,5,145,35},
{145,35,170,85},
{170,85,130,50},


   
        
    };
           


    /**
     * Creates new form DPoligono
     */
    public DPoligonoTraslacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        Lienzo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        TX = new javax.swing.JTextField();
        TY = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Tamanio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        jButton1.setText("dibujo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TX.setText("0");
        TX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXActionPerformed(evt);
            }
        });

        TY.setText("0");

        jLabel1.setText("tx");

        jLabel2.setText("ty");

        jButton2.setText("↑");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("↓");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("←");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("→");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("↖");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("↙");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("↗");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("↘");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        Tamanio.setText("0");

        jLabel3.setText("zoom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tamanio, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TY)
                                    .addComponent(TX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(TY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton6)
                            .addComponent(jButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton7)
                            .addComponent(jButton9))
                        .addGap(214, 214, 214))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        float zoom = Float.parseFloat(Tamanio.getText());

         for(int i=0;i<poligono.length;i++){
              x1 = poligono [i][0];
              y1 = poligono [i][1];
              x2 = poligono [i][2];
              y2 = poligono [i][3];
              l = new Linea(x1,y1,x2,y2);
              l.ColorLinea(240,240,240);
              l.trazaBrezenham(g);
              }
         
              for(int i=0;i<poligono.length;i++){
                 poligono [i][0] = (int) (zoom*poligono [i][0]);
                 poligono [i][1] = (int) (zoom*poligono [i][1]);
                 poligono [i][2] = (int) (zoom*poligono [i][2]);
                 poligono [i][3] = (int) (zoom*poligono [i][3]);
               }


         for(int i=0;i<poligono.length;i++){
             x1 = poligono [i][0];
             y1 = poligono [i][1];
             x2 = poligono [i][2];
             y2 = poligono [i][3];
             l = new Linea(x1,y1,x2,y2);
             l.ColorLinea(240,240,240);
             l.trazaBrezenham(g);
             }
         
              for(int i=0;i<poligono.length;i++){
                 poligono [i][0] +=4;
                 poligono [i][2] +=4;

            }
                 
                for(int i=0;i<poligono.length;i++){
                      x1 = poligono [i][0];
                      y1 = poligono [i][1];
                      x2 = poligono [i][2];
                      y2 = poligono [i][3];
                      l = new Linea(x1,y1,x2,y2);
                      l.trazaBrezenham(g);
                         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
    
     poligono [i][1] -=4;
     poligono [i][3] -=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
    
     poligono [i][1] +=4;
     poligono [i][3] +=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
    
     poligono [i][0] -=4;
     poligono [i][2] -=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        float zoom = Float.parseFloat(Tamanio.getText());
       
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
          for(int i=0;i<poligono.length;i++){
    poligono [i][0] = (int) (zoom*poligono [i][0]);
    poligono [i][1] = (int) (zoom*poligono [i][1]);
    poligono [i][2] = (int) (zoom*poligono [i][2]);
    poligono [i][3] = (int) (zoom*poligono [i][3]);
          }
          
          
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
     poligono [i][0] +=4;
     poligono [i][2] +=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
           Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
         poligono [i][0] +=4;
         poligono [i][1] -=4;
         poligono [i][2] +=4;
         poligono [i][3] -=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);}
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
           Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int tx = Integer.parseInt(TX.getText());
        int ty = Integer.parseInt(TY.getText());
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
     poligono [i][0] +=4;
     poligono [i][1] +=4;
     poligono [i][2] +=4;
     poligono [i][3] +=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
     poligono [i][0] -=4;
     poligono [i][1] +=4;
     poligono [i][2] -=4;
     poligono [i][3] +=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
           Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
       
        
          for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(240,240,240);
    l.trazaBrezenham(g);
        }
        for(int i=0;i<poligono.length;i++){
     poligono [i][0] -=4;
     poligono [i][1] -=4;
     poligono [i][2] -=4;
     poligono [i][3] -=4;
   
        }
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPoligonoTraslacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPoligonoTraslacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPoligonoTraslacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPoligonoTraslacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPoligonoTraslacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lienzo;
    private javax.swing.JTextField TX;
    private javax.swing.JTextField TY;
    private javax.swing.JTextField Tamanio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
