/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tgraficacion;
import java.awt.*;
/**
 *
 * @author Jose Eduardo Madrigal Osorio
 * 
 */
public class DPoligonoRotacion extends javax.swing.JFrame {
    
    int [][] poligono = {
        
 {130,50,110,50},
{110,50,90,90},
{90,90,115,155},
{115,155,135,180},
{135,180,170,150},
{170,150,155,235},
{155,235,160,290},
{160,290,150,330},
{150,330,160,290},
{160,290,155,235},
{155,235,170,150},
{170,150,170,235},
{170,235,174,280},
{174,280,181,280},
{181,280,185,235},
{185,235,185,150},
{185,150,200,235},
{200,235,195,290},
{195,290,205,330},
{205,330,195,290},
{195,290,200,235},
{200,235,185,150},
{185,150,220,180},
{220,180,240,155},
{240,155,265,90},
{265,90,245,50},
{245,50,225,50},
{225,50,185,85},
{185,85,210,35},
{210,35,205,5},
{205,5,210,35},
{210,35,185,85},
{185,85,185,50},
{185,50,181,30},
{181,30,182,29},
{182,29,183,28},
{183,28,181,30},
{181,30,174,30},
{174,30,170,50},
{170,50,174,30},
{174,30,173,29},
{173,29,174,28},
{174,28,174,30},
{174,30,170,50},
{170,50,185,50},
{185,50,169,50},
{169,50,170,85},
{170,85,145,35},
{145,35,155,5},
{155,5,145,35},
{145,35,170,85},
{170,85,130,50},
   
        
    };
           


    /**
     * Creates new form DPoligono
     */
    public DPoligonoRotacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lienzo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PX = new javax.swing.JTextField();
        PY = new javax.swing.JTextField();
        Angulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lienzo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout LienzoLayout = new javax.swing.GroupLayout(Lienzo);
        Lienzo.setLayout(LienzoLayout);
        LienzoLayout.setHorizontalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        LienzoLayout.setVerticalGroup(
            LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jButton1.setText("dibujo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("px");

        jLabel2.setText("py");

        jLabel3.setText("angulo");

        PX.setText("0");

        PY.setText("0");

        Angulo.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Angulo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(PY)
                            .addComponent(PX))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Angulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Graphics g = Lienzo.getGraphics();
        int x1;
        int y1;
        int x2;
        int y2;
        Linea l;
        int bx = Integer.parseInt(PX.getText());
        int by = Integer.parseInt(PY.getText());
        double alfa = Double.parseDouble(Angulo.getText());
        for(int i=0;i<poligono.length;i++){
    x1 = poligono [i][0];
    y1 = poligono [i][1];
    x2 = poligono [i][2];
    y2 = poligono [i][3];
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(255,255,255);
    l.trazaBrezenham(g);
        }
         
         for(int i=0;i<poligono.length;i++){
         x1 =bx+((int)Math.round((poligono[i][0]-bx)*Math.cos(Math.toRadians(alfa))))-((int)Math.round((poligono[i][1]-by)*Math.sin(Math.toRadians(alfa)))) ;
         y1 =by+((int)Math.round((poligono[i][0]-bx)*Math.sin(Math.toRadians(alfa))))+((int)Math.round((poligono[i][1]-by)*Math.cos(Math.toRadians(alfa)))) ;
         x2 =bx+((int)Math.round((poligono[i][2]-bx)*Math.cos(Math.toRadians(alfa))))-((int)Math.round((poligono[i][3]-by)*Math.sin(Math.toRadians(alfa)))) ;
         y2 =by+((int)Math.round((poligono[i][2]-bx)*Math.sin(Math.toRadians(alfa))))+((int)Math.round((poligono[i][3]-by)*Math.cos(Math.toRadians(alfa)))) ;     
     poligono [i][0] = x1;
     poligono [i][1] = y1;
     poligono [i][2] = x2;
     poligono [i][3] = y2;
    l = new Linea(x1,y1,x2,y2);
    l.ColorLinea(0,0,0);
    l.trazaBrezenham(g);
         } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DPoligonoRotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DPoligonoRotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DPoligonoRotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DPoligonoRotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DPoligonoRotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Angulo;
    private javax.swing.JPanel Lienzo;
    private javax.swing.JTextField PX;
    private javax.swing.JTextField PY;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
